#!/bin/bash
helpmessage() {
    echo "Usage: gestsea [option] [module]"
    echo "module = principal        - People/invoice management"
    echo "         parametrage      - Settings of the GestSEA (products, cities, types...)"
    echo "         comptabilite     - Accountancy"
    echo "         moto             - Settings of the Optimal Measure of Time of Occupation"
    echo "         temps            - Registration of the tasks day by day"
    echo "         reglement        - Management of the payments"
    echo "         na               - Management of the Non Adherents"
    echo "         cotisation_2008  - Registration of the cotisation (Format 2008)"
    echo "         personne         - Lists people (development only)"
    echo ""
    echo "option = -evo login       - Load EVO+ Excel file in database and make PDF"
    echo "         -h/-help/--help  - Print this message"
    echo "         -jc              - With Javascript Console"
}




if [ $# = 0 ]; then
    echo "Use 'gestsea --help' to display help message if necessary."
    /usr/local/bin/webbrowser-sql/firefox -chrome chrome://gestsea/content/
elif [ $# = 1 ]; then
    if [ $1 = "-h" ]; then
        helpmessage
        exit 1
    fi
    if [ $1 = "-help" ]; then
        helpmessage
        exit 1
    fi
    if [ $1 = "--help" ]; then
        helpmessage
        exit 1
    fi
    if [ $1 = "--stop" ]; then
        pkill firefox
        exit 1
    fi
    if [ $1 = "--restart" ]; then
        pkill firefox
        /usr/local/bin/webbrowser-sql/firefox -chrome chrome://gestsea/content/gestsea.xul
        exit 1
    fi
    if [ -e /usr/local/bin/gestsea/content/gestsea/$1.xul ]; then
        /usr/local/bin/webbrowser-sql/firefox -chrome chrome://gestsea/content/gestsea/$1.xul
    else
        echo "ERREUR : Le module $1 n'existe pas."
        helpmessage
        exit 1
    fi
elif [ $# = 2 ]; then
    if [ $1 = "-evo" ]; then
        /usr/local/bin/scripts/evoplus/gevo.sh $2
    fi
    if [ $1 = "-jc" ]; then
        if [ -e /usr/local/bin/gestsea/content/gestsea/$2.xul ]; then
            /usr/local/bin/webbrowser-sql/firefox -jsconsole -chrome chrome://gestsea/content/gestsea/$2.xul
        else
            echo "ERREUR : Le module $1 n'existe pas."
            helpmessage
            exit 1
        fi
    fi
else
    echo "Unvalid command"
    helpmessage
    exit 1
fi
