#!/bin/sh
if [ $# != 1 ]; then
    echo "Usage: savedb db_name"
    exit 1
fi
d=`date +%Y%m%d_%H%M`
f=db_$1_$d.sql
z=$f.tar.bz2
pg_dump -COx $1 -U brice > $f
tar cvjf $z $f
rm -f $f
cp $z /home/groupes/maintenance/backup/
scp $z 91.121.24.96:sauvegardes
rm -f $z
