#!/bin/bash
d=/usr/local/bin/scripts
dir=/home/groupes/comptabilite
f=www_fdsea33
cd $d
rm -f joomla.sql
psql gestsea -f web.sql
mv joomla.sql $f.sql
mv website_passwords.csv ${dir}/
tar cjvf $f.sql.tar.bz2 $f.sql
sudo -u brice scp $f.sql.tar.bz2 brice@www.fdsea33.fr:/home/backup/customs
rm -f $f.*
