


all:
	../../../../../firefox -chrome chrome://gestsea/content/generator/generator.xul

x:
	../../../../../firefox -chrome chrome://gestsea/content/

clean:
	rm -f *~ generator/*~ generator/sources/*~ gestsea/*~

