#!/bin/sh
if [ $# != 1 ]; then
    echo "Usage: reverse db_name"
    exit 1
fi
date=`date +%Y%m%d_%H%M`
database=$1
#file=${database}_${date}
file=${database}
psql $database -q -f sql2xml.sql > $file.xml
xsltproc -o ../documents/$file.html ../stylesheets/analysis-html.xsl $file.xml
rm -f *~
