#!/bin/sh
if [ $# != 1 ]; then
    echo "Usage: reverse db_name"
    exit 1
fi
date=`date +%Y%m%d_%H%M`
database=$1
file=${database}_${date}
psql $database -q -f sql2xml.sql > $file.xml
xsltproc -o $file.html ../scripts/stylesheets/analysis-html.xsl $file.xml
rm -f *~
